### ISSUE TITLE
Is there a way to list installed packages?

### ISSUE THREAD

**Issue by raindev** [clibs/clib#118] opened 2015-10-03 14:30 UTC
Haven't found any information about that online. Nothing like `list` is supported by the `clib` command. It wold be very useful to be able to list installed packages, obviously.

**Comment by nvartolomei** [comment] 2015-10-24 21:32
No.

In order to do this first clib would need to create a file for tracking this but it is too simple and lazy.

If you installed all packages to default directory then `ls deps` will help :)

**Comment by jwerle** [comment] 2015-10-24 21:39
Thanks @nvartolomei.
Hey @raindev - I'm closing this as `ls deps/` is simple enough :]

**Closed by jwerle** 2015-10-24 21:39 UTC

**Comment by raindev** [comment] 2015-10-25 10:34
Excuse my ignorance, but where is `deps/` located? I'm on OS X; use clib for standalone utilities  (like bpkg), not development dependencies. Thanks in advance

**Comment by tj** [comment] 2015-11-02 01:04
@raindev they're always local in ./deps

**Comment by raindev** [comment] 2015-11-02 09:57
Seme misunderstanding in here:
```
# Create new empty directory
machine:~ raindev$ mkdir clibs
machine:~ raindev$ cd clibs/
# Installing bpkg from within it
machine:clibs raindev$ clib install bpkg/bpkg
       fetch : bpkg/bpkg:package.json
  info: Welcome to the 'bpkg' installer!
  info: Checking for git...

  info: Creating temporary files...
  warn: Already exists: '/var/folders/9d/gj7l8v5j0rd8_vy8j4hvycg80000gn/T//bpkg-master'
  info: Fetching latest 'bpkg'...
  info: Installing...

  info: Uninstalling /usr/local/bin/bpkg...
  info: Installing /usr/local/bin/bpkg...
  info: Done!
# Checking the directory for any content
machine:clibs raindev$ ls -a
.  ..
# There should be deps/ :|
machine:clibs raindev$ ls deps
ls: deps: No such file or directory
```

**Comment by jwerle** [comment] 2015-11-02 12:28
@raindev bpkg defines an `install` property in its package.json file. This is intended for "global" executables or libraries. bpkg is a command therefore wouldn't be installed in the `deps/` directory. The same could be said for any clib package that has that property in its package.json

**Comment by raindev** [comment] 2015-11-02 16:56
Considering the revelations, the issue is still open. I've updated the title to reflect the problem more precisely.

**Comment by raindev** [comment] 2015-11-13 07:38
So, no plan's to support listing of global packages?

**Comment by reubano** [comment] 2015-11-13 08:29
Agreed. `clib-list` would be very useful. It's understandable if you don't have time to implement this at the moment. But I think reopening the issue is a good idea.
