### ISSUE TITLE
support for clone and subtree

### ISSUE THREAD

**Issue by MauroMombelli** [clibs/clib#114] opened 2015-06-06 23:33 UTC
This utility would be perfect to manage my shared dependency, if only had an option to use git's subtree (or clone, if target directory is not part of a repository) instead of fetch. Bonus point if look of subtree repo has been forked by principal repo user, and ask change the push remote.

The advantage of this system is to make easier to share the modification to the library between collaborator, but also to make easier to make pull-request.

The repository should be created in a way they are good to be directly cloned; just code, licence, README.md, and the package.json.

The test code can be placed in a different repository, witch obviously add the "code repository" as submodule dependency

this is what i do for my project, see https://github.com/MauroMombelli/FreeDCM_test

Edit: found out subtree are more appropriate than submodule

**Comment by jwerle** [comment] 2020-07-23 13:01
Possible duplicate of #105

**Closed by jwerle** 2020-07-23 13:01 UTC
